# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_match', '0002_image_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploaded_images/images')),
                ('features', picklefield.fields.PickledObjectField(default=0, editable=False)),
            ],
        ),
    ]
